name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'New'
    label: 'type: feature'
  - title: 'Bug Fixes'
    label: 'type: bug'
  - title: 'Performance'
    label: 'type: performance'
  - title: 'Security'
    label: 'type: security'
  - title: 'Deprecations'
    label: 'type: deprecation'
  - title: 'Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
      - 'type: deprecation'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: performance'
      - 'type: security'
      - 'type: docs'
      - 'type: dependencies'

exclude-labels:
  - 'skip-changelog'
