#!/usr/bin/env bash
# MISE description="Run JVM tests"

set -e

echo "Running JVM tests..."

./mill -i -k -j 0 \
    "morphir.__.jvm.__.compile" \
    + \
    "morphir.__.jvm.publishArtifacts" \
    + \
    "morphir.__.jvm.__.test"

echo "JVM tests completed successfully"
