#!/usr/bin/env bash
# MISE description="Run Runtime JVM tests"

set -e

echo "Running Runtime JVM tests..."

./mill -i -k -j 0 \
    "morphir.runtime.jvm.__.compile" \
    + \
    "morphir.runtime.jvm.publishArtifacts" \
    + \
    "morphir.runtime.jvm.__.test"

echo "Runtime JVM tests completed successfully"
